= C4 named behaviors

While types are not specified in C4, a given value may have some more complex behavior attached to it.
The most basic example is a list that can be constructed using only built-in elements, yet having a concrete name for the set of related functions/operators.
These types are usually implemented in a way that they have some internal, unspecified type and rely on the implementation, but this may not be the case always.

[IMPORTANT]
====
These behaviors only serve as documentational features. Nothing stops in C4 to pass `42` to a function that expects a `List`, some cases this may even be an intended behavior.
====

Each behavior has a name, at least one constructor (a function that returns a type that acts like the given behavior), and zero or more operators and function that take this behavior as an operand.

== Range

A range behavior is a series of integer types that follow each other by a predefined increment, usually 1.

=== Constructors

`make_range_step/3 Int@from Int@to Int@inc -> *Range`::
Generates a range type that starts at the value of `from`, and goes until the value of `to` (exclusive) in increments of `inc`.
If some `x >= to` cannot be reached by repeatedly adding `inc` to `from`, the result is an empty range.

`make_irange_step/3 Int@from Int@to Int@inc -> *Range`::
Generates a range type that starts at the value of `from`, and goes until the value of `to` (inclusive) in increments of `inc`.
Equivalent to `make_range_step from (successor to) inc`.

`make_range/2 Int@from Int@to -> *Range`::
Equivalent to `make_range_step from to 1`.

`make_irange/2 Int@from Int@to -> *Range`::
Equivalent to `make_irange_step from to 1`.

`(..)/2 Int Int -> *Range`:: See xref:./c4ops.adoc[c4ops].

`(\...)/2 Int Int -> *Range`:: See xref:./c4ops.adoc[c4ops].

=== Operations

`(:>>) *Range Int -> Bool`::
Determines if an integer is the range.
A value is only part of a range, if by stepping using the range's step value lands on the given integer.

`(<<:) Int *Range -> Bool`::
Determines if an integer is the range.
A value is only part of a range, if by stepping using the range's step value lands on the given integer.


