= C4 metadocs

This document describes how the documentation of C4 is laid out.
Lists the available documentation pages, and contains information about how to interpret the documentation itself.

== Pages

xref:./c4lang.adoc[c4lang]:: Description of the C4 language.
xref:./c4ops.adoc[c4ops]:: Listing of all available built-in operators.
xref:./c4docs.adoc[c4docs]:: This metadocs page.
xref:./c4guts.adoc[c4guts]:: Description of internals the current implementation of C4.

== Interpretations

=== Function and operator typing

While C4 is dynamically typed, it can and will coerce values to fit the wanted types of arguments in function and operator calls.
How these functions and operators expect their arguments is defined in the following format:

----
foo/2 A B -> R
(op)/2 A B -> R
(op)/1 A -> R
----

Where `foo` is a function (binding that contains a block) and `op` is an operator, and the uppercase letters are type specifiers.
They describe what a given type may be, and if a value that does not match this will be coerced.

[table,cols="1,4"]
|====
| Type specifier | Meaning

| Any
| Any/an unknown type. Usually because it is unread by the function/operator, just passed as-is to somewhere else.

| Bool
| Any value that is interpreted as true, or the empty block which is interpreted as false.

| Int
| A 32-bit or 64-bit integer.

| String
| A string.

| Float
| A 64-bit IEEE754 floating point number.

| Block
| A block value.

| A \| B
| Either type specifier A or type specifier B.

| A@foo
| Type specifier A that can be referenced later in the function/operator type specifier by the name `foo`.

| #foo
| Backreference to a type specifier that can be referenced with name `foo`.

| *Foo
| An unspecified type that acts as a named behavior as specified in xref:./c4acts.adoc[c4acts].
|====

As an example see the following type specifiers:

----
if/3 Bool Block Block -> Any <1>
else/1 Any@input -> #input <2>
(+)/2 Int Int -> Int <3>
(,)/2 Any *List -> *List <4>
----
<1> Defines the `if/3` function. Since the returned value is dependent on the runtime value of the Bool parameter and the result types of the given and chosen Block parameters the return type is just Any.
<2> The `else/1` function takes any type and returns it as-is.
<3> The `(+)/2` function perform integer addition and thusly takes two ints and returns an int.
<4> The `,` operator creates a list as defined in a named behavior called `List`.