= C4 built-in operators (c4ops)

This document describes the list of all operators built-in to C4.
They are categorized semantically.

== Untyped operators

These operators do not require any specific type to defined their behavior correctly.

`(=)/2 Any Any -> Bool`::
Returns whether the given two operands have the same type and same value.

`(==)/2 Any Any -> Bool`::
Equivalent to `(=)/2`.

`(<>)/2 Any Any -> Bool`::
Returns whether the given two operands have either a different type or a different value.
The opposite of `(=)/2`.

`(!=)/2 Any Any -> Bool`::
Equivalent to `(<>)/2`.

== Integral operators

These operators take integer arguments and either return an integer from the result as an arithmetic operation or perform some other, usually more complex, calculation.

`(+)/2 Int Int -> Int`::
Performs signed integer addition.
Uses the smallest available integer type as the result (32 or 64 bit).
As the operation is performed as signed values, and overflowing the 64 bit value is undefined as of now.

`(+')/2 Int Int -> Int`::
Performs unsigned integer addition.
Uses the smallest available integer type as the result (32 or 64 bit).
As the operation is performed as unsigned values, and overflowing the 64 bit value results in wraparound.

`(-)/2 Int Int -> Int`::
Performs signed integer subtraction.
Uses the smallest available integer type as the result (32 or 64 bit).
As the operation is performed as signed values, and overflowing the 64 bit value is undefined as of now.

`(-')/2 Int Int -> Int`::
Performs unsigned integer subtraction.
Uses the smallest available integer type as the result (32 or 64 bit).
As the operation is performed as unsigned values, and overflowing the 64 bit value results in wraparound.

`(-)/1 Int -> Int`::
Negates a given value.
The input and result are interpreted as signed value of the smallest available integer type (32 or 64 bit) that fits the value.

`(+)/1 Any@inp -> #inp`::
Unary plus operator that does nothing.
Can be used to emphasise that a given value is positive.
(It can still be negative, as `{plus}(-1)` is still `-1`.)

`(*)/2 Int Int -> Int`::
Performs signed integer multiplication.
Uses the smallest available integer type as the result (32 or 64 bit).
As the operation is performed as signed values, and overflowing the 64 bit value is undefined as of now.

`(*')/2 Int Int -> Int`::
Performs unsigned integer multiplication.
Uses the smallest available integer type as the result (32 or 64 bit).
As the operation is performed as unsigned values, and overflowing the 64 bit value results in wraparound.

`(/)/2 Int Int -> Int`::
Performs signed integer division.
Fractional results are rounded down.
Uses the smallest available integer type as the result (32 or 64 bit).
As the operation is performed as signed values, and overflowing the 64 bit value is undefined as of now.

`(/')/2 Int Int -> Int`::
Performs unsigned integer division.
Fractional results are rounded down.
Uses the smallest available integer type as the result (32 or 64 bit).
As the operation is performed as unsigned values, and overflowing the 64 bit value results in wraparound.

`(%)/2 Int Int -> Int`::
Returns the (possibly negative) remainder of the integer division.
Uses the smallest available integer type as the result (32 or 64 bit).
As the operation is performed as signed values, and overflowing the 64 bit value is undefined as of now.

`(%%)/2 Int@a Int -> Int`::
True modulus operator that always returns the remainder of the integer division mapped into the `[0, a]` interval.

`(..)/2 Int Int -> *Range`::
Creates an unspecified type that acts as an exclusive range.
Equivalent to calling `make_range` with the same parameters.

`(\...)/2 Int Int -> *Range`::
Creates an unspecified type that acts as an inclusive range.
Equivalent to calling `make_irange` with the same parameters.

`(+-)/2 Int@a Int@b -> *Range`::
Creates an inclusive range from `a + b` to `a - b` as if via `make_irange a + b a - b`.

`(-+)/2 Int@a Int@b -> *Range`::
Creates an inclusive range from `a - b` to `a + b` as if via `make_irange a - b a + b`.

`(|)/2 Int Int -> Int`::
Calculates the binary OR-ed value of the input values.
The result is the smallest sized integer that can fit all bits of the larger operand.
If the input operands have a different size, the smaller one is *zero extended*.

`(|^)/2 Int Int -> Int`::
Calculates the binary OR-ed value of the input values.
The result is the smallest sized integer that can fit all bits of the larger operand.
If the input operands have a different size, the smaller one is *sign extended*.

`(&)/2 Int Int -> Int`::
Calculates the binary AND-ed value of the input values.
The result is the smallest sized integer that can fit all bits of the larger operand.
If the input operands have a different size, the smaller one is *zero extended*.

`(&^)/2 Int Int -> Int`::
Calculates the binary AND-ed value of the input values.
The result is the smallest sized integer that can fit all bits of the larger operand.
If the input operands have a different size, the smaller one is *sign extended*.

`(^)/2 Int Int -> Int`::
Calculates the binary XOR-ed value of the input values.
The result is the smallest sized integer that can fit all bits of the larger operand.
If the input operands have a different size, the smaller one is *zero extended*.

`(^^)/2 Int Int -> Int`::
Calculates the binary XOR-ed value of the input values.
The result is the smallest sized integer that can fit all bits of the larger operand.
If the input operands have a different size, the smaller one is *sign extended*.

`(~)/1 Int -> Int`::
Calculates the binary NOT-ed value of the input value.
The result is the same sized integer as the input value.

== Float operators

These operators perform floating point operations.
Usually floating point arithmetic.

`(+.)/2 Float Float -> Float`::
Calculates the sum of two 64-bit float values.

`(-.)/2 Float Float -> Float`::
Calculates the difference of two 64-bit float values.

`(*.)/2 Float Float -> Float`::
Calculates the multiple of two 64-bit float values.

`(/.)/2 Float Float -> Float`::
Calculates the dividend of two 64-bit float values.

`(%.)/2 Float Float -> Float`::
Calculates the floating point remainder of the division of two 64-bit float values.

`(%%.)/2 Float@a Float -> Float`::
Calculates the floating point true modulus of the division of two 64-bit float values.
Always within the `[0, a]` interval.

== String operators

These operators take part in some kind of string manipulation.

`(+#)/2 String String -> String`::
Concatenates two strings.

`(*#)/2 String Int@n -> String`::
Concatenates the input string after itself `n` times.

== Logic operators

These operators perform boolean algebra.

`(&&)/2 Bool Bool -> Bool`:: Boolean AND.
`(||)/2 Bool Bool -> Bool`:: Boolean OR.
`(^||)/2 Bool Bool -> Bool`:: Boolean XOR.
`(\->)/2 Bool Bool -> Bool`:: Boolean implication.
`(!)/1 Bool -> Bool`:: Boolean NOT.
