= C4 interpreter

The C4 interpreter runs on top of LLVM's JIT infrastructure.

== Memory representation

[#general_technique]
=== General technique

Values are represented using NaN-boxing.
This means that values by themselves masquerade themselves as 64 bit IEEE754 floating point values, while in reality they could wrap more interesting datastructures.

The type used to wrap all this is called a datum (`datum_t`).
A datum is the memory area that stores a value which arises from the abstract notion of interpreting the bits stored in the datum.
The followings mostly talk about values since most things also care about the actual interpretation of a chunk of memory rather than just the naked bits.

This requires two things:

1. 64 bit IEEE754 floating point values, which provide the space to use.
2. 48 bit (or less) virtual addressing on the hardware running the interpreter.
This is true as of now for x86-64 and ARM64 so basically most relevant hardware.

In theory the memory representation could be generalized to use a less-tricky but more memory expensive and possibly slower solution if the hardware does not support it, but as of now this is not implemented.

.The bits used in different representations
-----
legend:
    N - The bits designating a NaN.
    R - Remoteness (see below)
    T - The type of data encoded
    D - A 64-bit double value
    P - A 48-bit pointer value
    I - A 32-bit integer value
    C - A 8-bit integer value
    × - Unused bits
    1 - set bit
    0 - unset bit

|              |         1         2         3         4         5         6    |
|              |1234567890123456789012345678901234567890123456789012345678901234|
|--------------|----------------------------------------------------------------|
| 64-bit float |DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD|
| True NaN     |NNNNNNNNNNNNTTTT××××××××××××××××××××××××××××××××××××××××××××××××|
| 32-bit int   |RNNNNNNNNNNNTTTT××××××××××××××××IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII|
| 48-bit ptr   |RNNNNNNNNNNNTTTTPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP|
| SSO string   |RNNNNNNNNNNNTTTTCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC00000000|
| empty block  |RNNNNNNNNNNNTTTT000000000000000000000000000000000000000000000000|
-----

When a double value is not a NaN value, it is a normal double, without any strings attached (pun intended).
The following values are encoded, in order of bits used:

Remoteness::
Whether a given value is directly encoded in the relevant bits, or has to be looked up through a pointer.
In this case, the mantissa bits always encode a pointer, and the type bits encode the type the pointer is pointing at.
A special case is taken when the type denotes a "True NaN", i.e. a NaN value that we want to use as an actual NaN.
In this case the Remoteness bit is not modified and ignored.

Type::
The four bits at the top of the mantissa denote the type encoded.
Together with the Remoteness bit, they specify how to interpret the remaining bits in the mantissa.
The types and their bit-patterns are in the table <<types>>.

Value::
The remaining 48 bits are the bits used to store the given values.

.NaN encoded types
[#types, table,cols="1,2,2,2"]
|====
| Remote | Type bits | Type | Value bits

| Untouched
| `0000`
| True NaN
| Untouched

| `0`
| `0001`
| The empty block
| Full zero

| `1`
| `0001`
| Block
| 48 bits as pointer to block

| `0`
| `0010`
| Integer
| 32 bits as integer

| `1`
| `0010`
| Long Integer
| 48 bits as pointer to 64 bit integer value

| `0`
| `0011`
| --
| --

| `1`
| `0011`
| Big Integer
| 48 bits as pointer to arbitrary size integer type

| `0`
| `0101`
| --
| --

| `1`
| `0101`
| Big Float
| 48 bits as pointer to arbitrary precision float type

| `0`
| `0100`
| SSO string
| Last 8 bits are unset, previous 32 bits each encode a "character" value, up-to 5 ASCII chars

| `1`
| `0100`
| String
| 48 bits as pointer to string value
|====

=== Floating point numbers

Floating point numbers are natively 64 bit values.
They follow IEEE754 representation.
They are the least tricky values, since everything that happens to them is as expected from other IEEE754 reliant implementations.

The NaN representation is hijacked as described in <<general_technique>>.

=== Integers

Integers start out as 32-bit values if either the literal representing them or the calculation producing them allows such.
They are encoded in the lower 32 bits of a 64 bit value.
If a literal does not fit in 32 bits it is encoded as a 64 bit value, as are calculations whose return value would overflow 32 bits.
This auto-mapping is performed by the C interface which only provides 64-bit interfaces.
These interfaces hide the fact that the given value is either a 32-bit value that got embedded into a 64-bit (double) value or a true 64-bit value allocated on a heap somewhere.
(They could also perform coercion but that is irrelevant now.)

=== Big Numbers

Arbitrary number values can be represented using native code: either BigInteger or BigFloats.
They are encoded into a pointer value pointing to the proper data structure.

TODO: These are not yet implemented.

=== Strings

> Strings are always shady.

The strings in the C4 runtime are immutable and shared across the process.
In this case, the string representation points to a shared memory pool of strings where the pointer points to the first real byte of the string.
The values are NUL terminated to allow easy interop with C functions that require so, but for built-in functions the length of the string is available in the previous 8 bytes count back from where the string pointer points.
Before that is a reference count.

.String encoding
-----
          RNNNNNNNNNNNTTTTPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
C4 datum: 1111111111110100PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                           This a pointer value that points somewhere, lets
                           say here ──────────────────────────────────────────┐
   0x0001 0x0000001C this is some string in UTF-8\0                           │
   ^      ^          ^                                                        │
   │      │          └────────────────────────────────────────────────────────┘
   │      │          This means the following three things:
   │      │    1. From here on follows a string in UTF-8 that is NUL terminated
   │      │       and therefore can be passed to most C functions (that can
   │      │       handle UTF-8 encoded strings...).
   │      │    2. The *previous* 8 bytes store the length of the string w/o the
   │      │       NUL terminator. Here: ┐
   │      └─────────────────────────────┘
   │           3. Reference counter. 10 bytes *before* the given pointer,
   │              2 bytes long. Here: ┐
   └──────────────────────────────────┘
-----

The special case happens when the reference count would overflow: the string is copied with a new reference count.

==== Short String Optimization

Other than this C4 performs SSO: strings shorter than 5 characters are encoded in place of the pointer.
In this case the 6th byte's value is always zero to ensure that there is always a terminating NUL.
These SSO strings are not immutable because they are copied wherever they go, so modifications can happen in-place.
If a string is inlined this way, the `Remotness` bit is zero.

This allows eliding allocation strings that are small enough.
Other than this, they are copied values,
